# TODO: dynamic NUM_TOPICS
LDA_NUM_TOPICS = 50
LDA_NUM_WORDS = 30

DEFAULT_NLP = "spacy"

FILE_TOPICS_VIZ_NAME = "topics.html"

FILE_MAX_CNT = 10e7

UNKNOWN_TOPIC_NUM = -1

TOK_FILTER_NO_BELOW_DOC = 2
TOK_FILTER_KEEP_N = 150000
TOK_FILTER_NO_ABOVE = 0.8
TOK_FILTER_KEEP_TOKENS = []

LDA_ITERATIONS = 100
LDA_PASSES = 100
